export const ADD_TO_CART ="ADD_TO_CART";
export const REMOVE_CART ="REMOVE_CART";
export const INCREASE_CART ="INCREASE_CART";
export const DECREASE_CART ="DECREASE_CART";
export const CHANGE_NUM_BY_KEY ="CHANGE_NUM_BY_KEY"

// export const CHECKED_CART 
export const GET_LIST_ORDER = "GET_LIST_ORDER"
export const UNCHECKED_ORDER ="UNCHECKED_ORDER"
export const LOAD_NEW_ORDER = "LOAD_NEW_ORDER"